version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8099:8099"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./fastapi:/mnt/fastapi
    command: -- --update=airup_shelf,base_rest_demo
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      #- PGDATA=/var/lib/postgresql/data/pgdata
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      #- odoo-db-data:/var/lib/postgresql/data/pgdata
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
